Repository force-h2020/force-bdss, pull requests merged in 2020-01, with the labels that each got.

#245 CI: added test coverage and tests diff
  ci/__main__.py
Labels: enhancement

#244 Base CSV Writer for MCO Events
  ci/__main__.py
  force_bdss/api.py
  force_bdss/app/optimize_operation.py
  force_bdss/core_driver_events.py
  force_bdss/io/base_csv_writer.py
  force_bdss/io/tests/test_base_csv_writer.py
  force_bdss/mco/base_mco_model.py
  force_bdss/tests/test_core_driver_events.py
Labels: enhancement, wip

#253 BUG: fixed FixedMCOParameter UI setup bug. Changed the type to Any
  force_bdss/mco/parameters/mco_parameters.py
  force_bdss/mco/parameters/tests/test_mco_parameters.py
Labels: bug

#255 BUG: creating ListedMCOParameter via UI
  force_bdss/mco/parameters/mco_parameters.py
Labels: bug

#243 DEV: Optimizer Engine classes
  ci/__main__.py
  force_bdss/api.py
  force_bdss/mco/optimizer_engines/__init__.py
  force_bdss/mco/optimizer_engines/base_optimizer_engine.py
  force_bdss/mco/optimizer_engines/space_sampling.py
  force_bdss/mco/optimizer_engines/tests/__init__.py
  force_bdss/mco/optimizer_engines/tests/test_base_optimizer_engine.py
  force_bdss/mco/optimizer_engines/tests/test_utilities.py
  force_bdss/mco/optimizer_engines/tests/test_weighted_optimizer.py
  force_bdss/mco/optimizer_engines/utilities.py
  force_bdss/mco/optimizer_engines/weighted_optimizer_engine.py
  force_bdss/mco/parameters/mco_parameters.py
  force_bdss/mco/parameters/tests/test_mco_parameters.py
  force_bdss/tests/dummy_classes/optimizer_engine.py
Labels: enhancement

#257 Renamed the Workflow.mco to Workflow.mco_model
  force_bdss/app/evaluate_operation.py
  force_bdss/app/optimize_operation.py
  force_bdss/app/tests/test_evaluate_operation.py
  force_bdss/app/tests/test_optimize_operation.py
  force_bdss/app/tests/test_workflow_evaluator.py
  force_bdss/app/workflow_evaluator.py
  force_bdss/core/tests/test_verifier.py
  force_bdss/core/tests/test_workflow.py
  force_bdss/core/workflow.py
  force_bdss/io/tests/test_workflow_reader.py
  force_bdss/io/tests/test_workflow_writer.py
  force_bdss/io/workflow_reader.py
  force_bdss/io/workflow_writer.py
  force_bdss/tests/fixtures/test_dummy.json
  force_bdss/tests/fixtures/test_empty.json
  force_bdss/tests/fixtures/test_null.json
  force_bdss/tests/fixtures/test_probe.json
Labels: enhancement, wip

#261 FIX: Workflow Reader changes json data
  force_bdss/io/tests/test_workflow_reader.py
  force_bdss/io/workflow_reader.py
Labels: enhancement

#262 FIX: Build status reference in README
  README.rst
Labels: bug

#263 MAINT: Workflow IO classes structure and error handling refactoring
  force_bdss/api.py
  force_bdss/app/tests/test_workflow_file.py
  force_bdss/app/workflow_file.py
  force_bdss/core/base_model.py
  force_bdss/core/data_value.py
  force_bdss/core/execution_layer.py
  force_bdss/core/factory_registry.py
  force_bdss/core/input_slot_info.py
  force_bdss/core/kpi_specification.py
  force_bdss/core/output_slot_info.py
  force_bdss/core/slot.py
  force_bdss/core/tests/test_execution_layer.py
  force_bdss/core/tests/test_workflow.py
  force_bdss/core/workflow.py
  force_bdss/core_driver_events.py
  force_bdss/data_sources/base_data_source.py
  force_bdss/data_sources/base_data_source_model.py
  force_bdss/data_sources/tests/test_base_data_source_model.py
  force_bdss/io/tests/test_workflow_reader.py
  force_bdss/io/tests/test_workflow_writer.py
  force_bdss/io/workflow_reader.py
  force_bdss/io/workflow_writer.py
  force_bdss/mco/base_mco_factory.py
  force_bdss/mco/base_mco_model.py
  force_bdss/mco/optimizer_engines/base_optimizer_engine.py
  force_bdss/mco/parameters/base_mco_parameter.py
  force_bdss/mco/parameters/tests/test_base_mco_parameter.py
  force_bdss/mco/tests/test_base_mco_factory.py
  force_bdss/mco/tests/test_base_mco_model.py
  force_bdss/tests/fixtures/test_failing_workflow_reader.json
  force_bdss/tests/fixtures/test_workflow_reader.json
  force_bdss/tests/fixtures/test_workflow_reader_v1.json
  force_bdss/tests/probe_classes/data_source.py
  force_bdss/tests/probe_classes/notification_listener.py
Labels: enhancement

#268 MAINT: remove workflow evaluator
  .gitignore
  force_bdss/api.py
  force_bdss/app/optimize_operation.py
  force_bdss/app/tests/test_workflow_evaluator.py
  force_bdss/app/workflow_evaluator.py
  force_bdss/core/tests/test_workflow.py
  force_bdss/core/workflow.py
  force_bdss/mco/optimizer_engines/tests/test_base_optimizer_engine.py
Labels: enhancement

#270 Dev: Workflow event types
  force_bdss/app/optimize_operation.py
  force_bdss/app/tests/test_optimize_operation.py
  force_bdss/core/tests/test_workflow.py
  force_bdss/mco/base_mco_model.py
  force_bdss/mco/tests/test_base_mco_model.py
Labels: enhancement

#273 MAINT: using tempfile instead of persistent `tmp.json` in tests
  force_bdss/io/tests/test_workflow_writer.py
Labels: enhancement

#274 ENH: Include WeightedMCOStartEvent and WeightedMCOProgressEvent
  force_bdss/app/tests/test_optimize_operation.py
  force_bdss/core_driver_events.py
  force_bdss/mco/base_mco.py
  force_bdss/mco/base_mco_model.py
  force_bdss/mco/tests/test_base_mco.py
  force_bdss/mco/tests/test_base_mco_model.py
  force_bdss/tests/test_core_driver_events.py
Labels: enhancement

#275 MAINT: Port BaseDriverEvent (de)serialization from wfmanager
  force_bdss/core_driver_events.py
  force_bdss/tests/test_core_driver_events.py
Labels: enhancement

#277 FIX: Included missing Exception types in API
  force_bdss/api.py
Labels: bug

#278 FIX: BaseCSVWriter bug caused by WeightedMCOStartEvent serialize method mutating attribute
  force_bdss/api.py
  force_bdss/events/mco_events.py
  force_bdss/notification_listeners/base_csv_writer.py
  force_bdss/notification_listeners/tests/test_base_csv_writer.py
Labels: bug
